import { normalizeStoryAnalysis, type ImpactItem, type StoryAnalysis } from "@/src/lib/analysis";

function Confidence({ value }: { value: string }) { return <span className={`analysis-confidence confidence-${value.toLowerCase()}`}>{value} confidence</span>; }
function Sources({ refs }: { refs: string[] }) { return refs.length ? <span className="analysis-sources">Sources: {refs.join(" · ")}</span> : <span className="analysis-sources">Evidence not sufficient for a source-supported conclusion</span>; }
function ImpactList({ items, empty = "Insufficient information to determine the effect reliably." }: { items: ImpactItem[]; empty?: string }) { return items.length ? <div className="analysis-list">{items.map((item) => <div className="analysis-item" key={`${item.subject}-${item.effect}`}><div className="analysis-item-heading"><strong>{item.subject}</strong><Confidence value={item.confidence} /></div><p>{item.effect}</p>{item.mechanism && <p className="analysis-mechanism"><strong>Mechanism:</strong> {item.mechanism}</p>}<Sources refs={item.sourceRefs} /></div>)}</div> : <p className="analysis-empty">{empty}</p>; }

export function StoryAnalysisSections({ value }: { value: unknown }) {
  const analysis = normalizeStoryAnalysis(value);
  if (!analysis) return <section className="story-section"><h2>Impact analysis</h2><p>Detailed business and market impact analysis is not available for this story yet. The application will say so rather than infer unsupported effects.</p></section>;
  return <>
    <section className="story-section"><h2>What happened</h2>{analysis.whatHappened.split(/\n\s*\n/).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section>
    <section className="story-section"><h2>Direct impact</h2><ImpactList items={analysis.directImpact} /></section>
    <section className="story-section"><h2>Indirect impact</h2><ImpactList items={analysis.indirectImpact} /></section>
    <section className="story-section"><h2>Impact on people</h2><ImpactList items={analysis.peopleImpact} /></section>
    {analysis.entityDetails.companies.length + analysis.entityDetails.industries.length + analysis.entityDetails.countries.length + analysis.entityDetails.markets.length > 0 && <section className="story-section"><h2>Business intelligence</h2><div className="entity-grid">{Object.entries({ Companies: analysis.entityDetails.companies, Industries: analysis.entityDetails.industries, Countries: analysis.entityDetails.countries, Markets: analysis.entityDetails.markets, "Potentially affected companies": analysis.entityDetails.potentiallyAffectedCompanies }).filter(([, values]) => values.length > 0).map(([label, values]) => <div className="entity-box" key={label}><div className="eyebrow">{label}</div><div>{values.join(" · ")}</div></div>)}</div></section>}
    <section className="story-section"><h2>Geographic impact</h2>{analysis.geographicImpact.length ? <div className="analysis-list">{analysis.geographicImpact.map((item) => <div className="analysis-item" key={item.location}><div className="analysis-item-heading"><strong>{item.location}</strong><Confidence value={item.confidence} /></div><p>{item.effect}</p><Sources refs={item.sourceRefs} /></div>)}</div> : <p className="analysis-empty">No specific geographic effect can be determined reliably from the available coverage.</p>}</section>
    <section className="story-section"><h2>Asset impact</h2>{analysis.assetImpact.length ? <div className="analysis-list">{analysis.assetImpact.map((item) => <div className="analysis-item" key={item.asset}><div className="analysis-item-heading"><strong>{item.asset}</strong><Confidence value={item.confidence} /></div><p>{item.whyItCouldBeAffected}</p><p className="analysis-mechanism"><strong>Transmission:</strong> {item.transmissionMechanism} · <strong>Direction:</strong> {item.direction}</p><Sources refs={item.sourceRefs} /></div>)}</div> : <p className="analysis-empty">No reliable asset connection is identified for this story.</p>}</section>
    {analysis.impactMap.length > 0 && <section className="story-section"><h2>Impact map</h2><div className="impact-map">{analysis.impactMap.map((step, index) => <span key={`${step}-${index}`}>{step}{index < analysis.impactMap.length - 1 && <b>↓</b>}</span>)}</div></section>}
    {analysis.followTheMoney.enabled && <section className="story-section"><h2>Follow the money</h2><div className="impact-map">{analysis.followTheMoney.steps.map((step, index) => <span key={`${step}-${index}`}>{step}{index < analysis.followTheMoney.steps.length - 1 && <b>↓</b>}</span>)}</div><p>{analysis.followTheMoney.explanation}</p><Confidence value={analysis.followTheMoney.confidence} /><Sources refs={analysis.followTheMoney.sourceRefs} /></section>}
    {analysis.supplyChain.length > 0 && <section className="story-section"><h2>Supply chain</h2><div className="analysis-list">{analysis.supplyChain.map((item) => <div className="analysis-item" key={`${item.stage}-${item.entity}`}><div className="analysis-item-heading"><strong>{item.stage}: {item.entity}</strong><Confidence value={item.confidence} /></div><p>{item.effect}</p><Sources refs={item.sourceRefs} /></div>)}</div></section>}
    {analysis.companyRelationships.length > 0 && <section className="story-section"><h2>Company relationships</h2><div className="analysis-list">{analysis.companyRelationships.map((item) => <div className="analysis-item" key={`${item.company}-${item.relationship}`}><div className="analysis-item-heading"><strong>{item.company}</strong><Confidence value={item.confidence} /></div><p>{item.relationship} · {item.effect}</p><Sources refs={item.sourceRefs} /></div>)}</div></section>}
  </>;
}
